coverage:
  status:
    project:
      default:
        # Fail the build if the coverage decreases by more than 1%
        threshold: 1%
        # Compare against the coverage of the most recent base commit
        target: auto
    patch: off

comment:
  layout: "reach, diff, flags, files"
  behavior: default
