name: Python build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    if: github.event_name != 'release'
    steps:
      - uses: actions/checkout@v6
      - uses: wagoid/commitlint-github-action@v6.2.1
        with:
          configFile: .commitlint.config.mjs

  build:
    needs: [commitlint]
    if: ${{ !cancelled() && needs.commitlint.result != 'failure' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
    env:
      SKIP: no-commit-to-branch
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-all.txt
        shell: bash
      - name: Cache pre-commit environments
        if: github.event_name != 'release'
        uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install pre-commit
        if: github.event_name != 'release'
        run: pip install pre-commit
        shell: bash
      - name: Run pre-commit
        if: github.event_name != 'release'
        run: pre-commit run --show-diff-on-failure --color=always --all-files
        shell: bash
      - name: Build midea-local
        run: python -m build
        shell: bash
      - name: Test with pytest
        run: |
          python -m pytest --rootdir . --cov=midealocal --cov-report html --cov-report xml --junitxml=reports/junit/junit.xml ./tests/
          mv htmlcov reports/coverage
        shell: bash
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs: [build]
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
        shell: bash
      - name: Build package
        run: python -m build
        shell: bash
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
